[package]
name = "librespot-tremor"
version = "0.2.0"
authors = ["Librespot Org"]
build = "build.rs"
description = "Rust bindings to tremor"
license = "MIT"

[dependencies]
libc = "0.2.65"
ogg-sys = "0.0.9"

[build-dependencies]
cc = "1.0.79"
pkg-config = "0.3"
